#!/usr/bin/env python3
"""Generate battle control glyph templates from original native-size PNGs; never run OCR."""
from pathlib import Path
import base64
import hashlib
import json
import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
ONE = "Tests/MirrorProbeCoreTests/Fixtures/active-battle-control-grid.png"
TWO = "Tests/MirrorProbeCoreTests/Fixtures/visual-battle-native-2x.png"
NATIVE_402 = "Tests/MirrorProbeCoreTests/Fixtures/native-402-battle-capture-0013.png"
REGIONS = {
    # Start below the changing party/footer border, even at the matcher's
    # one-logical-pixel upward offset. Keep the original lower edges.
    "skipControl": [(.075, .870, .09, .023)],
    "allAutoControl": [(.225, .870, .14, .021)],
    "pauseControl": [(.84, .626, .085, .024)],
    "retreatControl": [(.84, .655, .085, .024)],
}


def sample(path, region, dx=0, dy=0):
    bgr = cv2.imread(str(path), cv2.IMREAD_COLOR).astype(np.int32)
    gray = ((77*bgr[:, :, 2]+150*bgr[:, :, 1]+29*bgr[:, :, 0]) >> 8).astype(float)
    height, width = gray.shape
    x, y, w, h = region
    xx, yy = np.meshgrid((x+(np.arange(96)+.5)*w/96+dx)*width-.5,
                         (y+(np.arange(24)+.5)*h/24+dy)*height-.5)
    x0, y0 = np.floor(xx).astype(int), np.floor(yy).astype(int)
    tx, ty = xx-x0, yy-y0
    return ((1-ty)*((1-tx)*gray[y0, x0]+tx*gray[y0, x0+1])
            + ty*((1-tx)*gray[y0+1, x0]+tx*gray[y0+1, x0+1]))


def sources(marker):
    paths = [ONE, TWO]
    # Native 402x882 rasterization differs from the original 406x890/2x glyphs.
    # Only skip needs another sample; the other required controls already match.
    # Later incident frames remain replay inputs, not template calibration sources.
    if marker == "skipControl":
        paths.append(NATIVE_402)
    return [(path, REGIONS[marker][0]) for path in paths]


def main():
    lines = ["// Generated by Scripts/generate-battle-visual-templates.py; do not edit sample bytes.",
             "import Foundation", "", "struct VisualBattleTemplate {",
             "    let region: NormalizedRect", "    let pixels: [UInt8]", "}", "",
             "enum VisualBattleTemplates {", "    static let sampleWidth = 96",
             "    static let sampleHeight = 24",
             "    static let samples: [VisualBattleMarker: [VisualBattleTemplate]] = ["]
    manifest = []
    for marker in REGIONS:
        lines.append(f"        .{marker}: [")
        for path, region in sources(marker):
            raw = np.floor(sample(ROOT/path, region)+.5).astype(np.uint8).tobytes()
            encoded = base64.b64encode(raw).decode()
            x, y, w, h = region
            lines.extend([f"            // {path}",
                          f"            .init(region: .init(x: {x}, y: {y}, width: {w}, height: {h}),",
                          f'                  pixels: Array(Data(base64Encoded: "{encoded}")!)),'])
            manifest.append(dict(marker=marker, region=region, source=path,
                                 sourceSHA256=hashlib.sha256((ROOT/path).read_bytes()).hexdigest(),
                                 sampleSHA256=hashlib.sha256(raw).hexdigest()))
        lines.append("        ],")
    lines.extend(["    ]", "}", ""])
    (ROOT/"Sources/MirrorProbeCore/VisualBattleTemplates.swift").write_text("\n".join(lines))
    destination = ROOT/"DevelopmentFixtures/ClassifierReplaySources/auto-level-visual-inventory-20260911"
    destination.mkdir(parents=True, exist_ok=True)
    (destination/"battle-templates.json").write_text(json.dumps(manifest, indent=2)+"\n")


if __name__ == "__main__":
    main()
